feat: Throw DomException with name AbortError
sindresorhus/ky pull request #482
Opened 2023-01-11 14:51 UTC by cristobal

## Description
When throwing DomException it should provide `AbortError` name to the DomException constructor as specified in the MDN docs [here](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort)

![Screenshot 2023-01-11 at 15 49 58](https://user-images.githubusercontent.com/155505/211836956-edc26031-d3c8-4f64-be1f-00738c24af3b.png)

The PR also includes fallback to use of `Error` class where the `name` property is overridden.

This PR addresses and closes the following issue #470

2023-01-11 15:13 UTC, cristobal commented
The test get stuck for some reason, even when i run the tests locally on my Mac with latest node and from the main branch the tests are pending to finish.

2023-01-11 17:13 UTC, cristobal commented
Hmm tests run fine on node 14 on my Mac for both the main branch and this PR. 
Not sure why they CI failed then...

![Screenshot 2023-01-11 at 18 12 55](https://user-images.githubusercontent.com/155505/211871930-521db60b-49d0-456d-8658-03a77faa0285.png)

2023-01-11 18:42 UTC, cristobal commented
Seems that the pending tests do not work on the latest node 14.21.1, when running with node 14.19.3 as in the previous comment the tets work fine. However when running with 14.21.1 as in the picture below and the node version used to run the github workflow it fails also: 
![Screenshot 2023-01-11 at 19 39 45](https://user-images.githubusercontent.com/155505/211890765-09749032-a264-4c9d-b28f-71490fa16a07.png)

will try create a separate PR that addresses this issue 👋🏽

2023-01-12 01:23 UTC, sindresorhus requested changes

2023-01-12 01:23 UTC, sindresorhus commented on test/main.ts
> +	t.true(error.name === 'AbortError', `Expected AbortError, got ${error.name}`);
Use `t.is()`

2023-01-12 01:23 UTC, sindresorhus commented on source/errors/DOMException.ts
> +const domExceptionSupported = Boolean(globalThis.DOMException);
```suggestion
const isDomExceptionSupported = Boolean(globalThis.DOMException);
```

2023-01-12 01:23 UTC, sindresorhus commented on source/errors/DOMException.ts
> +	 */
```suggestion
	/*
	NOTE: Use DomException with AbortError name as specified in MDN docs (https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort)
	> When abort() is called, the fetch() promise rejects with an Error of type DOMException, with name AbortError.
	*/
```

2023-01-12 01:23 UTC, sindresorhus commented on test/main.ts
> +test('throws DomException/Error with name AbortError when aborted by user', async t => {
```suggestion
test('throws DOMException/Error with name AbortError when aborted by user', async t => {
```

2023-01-12 07:27 UTC, cristobal commented
@sindresorhus thanks for the feedback the requested changes have been addressed, also created a separate PR [here](https://github.com/sindresorhus/ky/pull/484), that addresses the flaky browsers tests 👋🏽

2023-01-13 07:54 UTC, sindresorhus commented
A test is failing on Node.js 18

2023-01-13 07:57 UTC, cristobal commented
> A test is failing on Node.js 18

Weird looking into to 👋🏽

2023-01-13 08:05 UTC, cristobal commented on test/main.ts
> +	t.true(['DomException', 'Error'].includes(error.constructor.name), `Expected DOMException or Error, got ${error.constructor.name}`);
```suggestion
	t.true(['DOMException', 'Error'].includes(error.constructor.name), `Expected DOMException or Error, got ${error.constructor.name}`);
```

2023-01-13 08:10 UTC, cristobal commented
@sindresorhus fixed was a typo in the test name should be `DOMException` not `DomException` my bad🤦🏽

2023-01-13 08:37 UTC, merged