fix: support cloudflare workers
sindresorhus/ky pull request #559
Opened 2024-02-22 18:36 UTC by riderx

This PR comes to fix the Cloudflare workers issue mentioned here with the solution:
https://github.com/sindresorhus/ky/issues/366#issuecomment-1670435774

2024-02-23 02:49 UTC, sindresorhus commented
CI is failing

2024-02-24 01:41 UTC, riderx commented
@sindresorhus fixed :)

2024-02-24 06:05 UTC, fregante requested changes

2024-02-24 06:05 UTC, fregante commented on source/core/Ky.ts
> +			credentials: isCredentialsSupported ? ((this._input as Request).credentials || 'same-origin') : 'same-origin',
I don’t think this is gonna work, `_options.credentials` should not be set at all, according to the error.

Also the comment is very outdated and we can probably use:

```suggestion
			credentials: isCredentialsSupported ? (this._input as Request).credentials : undefined,
```

… as long as CloudFlare accepts `{credentials: undefined}` and doesn't actually require `{}`

2024-02-24 21:00 UTC, riderx commented
Thanks @fregante i did update it.
I had to change the typing to make this solution work, and added a comment.
I did try and `{credentials: undefined}` is the required way for Cloudflare.
Since isCredentialsSupported is not reused, I wonder if that shouldn't be better, directly in the ternary?

2024-02-24 21:12 UTC, fregante approved these changes

2024-02-25 13:29 UTC, merged